AWSTemplateFormatVersion: "2010-09-09"
Description: "Amazon Bedrock KnowledgeBase with Kendra GenAI index for document retrieval and AI-powered search."

Parameters:
  ProjectName:
    Type: String
    Description: "Name of the project for resource naming and tagging"
    Default: "doc-qa"
    AllowedPattern: "^[a-zA-Z0-9-]+$"
    ConstraintDescription: "Must contain only alphanumeric characters and hyphens"

  S3BucketName:
    Type: String
    Description: "Name of the S3 bucket containing the knowledge base content"
    AllowedPattern: "^[a-z0-9.-]+$"
    ConstraintDescription: "Must be a valid S3 bucket name"

  S3BucketPrefix:
    Type: String
    Description: "S3 prefix/folder path for knowledge base content (without leading/trailing slashes)"
    Default: "data"

Resources:
  # IAM Role for Kendra Index
  KendraIndexRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: kendra.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${S3BucketName}"
                  - !Sub "arn:aws:s3:::${S3BucketName}/*"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: KendraIndex

  # Kendra Index
  KendraIndex:
    Type: AWS::Kendra::Index
    Properties:
      Name: !Sub "${ProjectName}-index"
      Description: "Kendra index for Bedrock KnowledgeBase document search and retrieval"
      Edition: "GEN_AI_ENTERPRISE_EDITION"
      RoleArn: !GetAtt KendraIndexRole.Arn
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: KendraIndex

  # IAM Role for Kendra Data Source
  KendraDataSourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: kendra.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3DataSourcePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${S3BucketName}"
                  - !Sub "arn:aws:s3:::${S3BucketName}/*"
              - Effect: Allow
                Action:
                  - kendra:BatchPutDocument
                  - kendra:BatchDeleteDocument
                Resource: !GetAtt KendraIndex.Arn
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: KendraDataSource

  # Kendra S3 Data Source (using modern TemplateConfiguration)
  KendraS3DataSource:
    Type: AWS::Kendra::DataSource
    Properties:
      Name: !Sub "${ProjectName}-s3-datasource"
      Description: "S3 data source for knowledge base content using template configuration"
      IndexId: !Ref KendraIndex
      Type: TEMPLATE
      RoleArn: !GetAtt KendraDataSourceRole.Arn
      DataSourceConfiguration:
        TemplateConfiguration:
          Template:
            connectionConfiguration:
              repositoryEndpointMetadata:
                BucketName: !Ref S3BucketName
            repositoryConfigurations:
              document:
                fieldMappings: []
            additionalProperties:
              inclusionPrefixes:
                - !Ref S3BucketPrefix
            type: "S3"
            syncMode: "FULL_CRAWL"
            version: "1.0.0"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: KendraDataSource

  KendraIndexIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ProjectName}/kendra/index/id"
      Type: String
      Value: !Ref KendraIndex
      Description: "Kendra Index ID"
      Tier: Standard
      Tags:
        Component: KendraIndex

Outputs:
  KendraIndexId:
    Description: "ID of the created Kendra index"
    Value: !Ref KendraIndex

  KendraIndexArn:
    Description: "ARN of the created Kendra index"
    Value: !GetAtt KendraIndex.Arn

  KendraDataSourceId:
    Description: "ID of the created Kendra data source"
    Value: !Ref KendraS3DataSource

  S3BucketConfiguration:
    Description: "S3 bucket and prefix configuration used"
    Value: !Sub "s3://${S3BucketName}/${S3BucketPrefix}"
